### ISSUE TITLE
An error should be raise when a worker is created with the wrong id

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PyGrid#304]

**Comment by Jasopaum** [comment]
Hi!
I wanted to work on this issue in order to get a bit more familiar with Grid but I'm not sure I understood everything about how Grid works.
First, do we agree that the issue to solve is when a user want to connect a WebsocketGridClient on a port where a web socket app is running but that the ids/names mismatch?
If this is right, I'm not sure where the check should be inserted in the code... Could someone help me a bit on that? :)

**Comment by IonesioJunior** [comment]
Nowadays, nodes send their own ids to the client after setting the connection
Fixed #342
