### ISSUE TITLE
are 2 types of grid clients really needed?

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PyGrid#325]
Currently, we support 2 types of grid clients: GridClients and WebsocketGridClients. Do we really need to support these both types of clients? Is there a scenario where we want a client to only use HTTP to communicate with other clients?

If not, I propose two options:

1. We could make GridClient an abstract class
2. We could rename WebsocketGridClient to GridClient.

**Comment by Quisher** [comment]
Why are we using sockets really. What’s the benefit over http?

**Comment by mari-linhares** [comment]
> Why are we using sockets really. What’s the benefit over http?

They're complementary. "websockets are a great choice for handling long-lived bidirectional data streaming in near real-time manner, whereas REST is great for occasional communications." - [Source](https://medium.com/platform-engineer/web-api-design-35df8167460)

WebSockets are great for sharing tensors and making a lot of requests in a small amount of time (we do a lot for SMPC).

**Comment by Quisher** [comment]
Then I guess the only use case would be for environments where we can’t use sockets. 

To be honest i think it’s nice... giving users the option. 
We can structure the code such that the networking stack is just a wrapper around the full grid lib. Would make it easy to support both. 

And abstract is such that the end user only gets exposed to a option of networkin_protocl: rest/sockets

**Comment by iamtrask** [comment]
Yup - this seems like a great idea! +1 from me!

**Comment by IonesioJunior** [comment]
Actually, socket.io protocol already implement both of them (We start new socket.io connection sending a pooling HTTP request asking to the server if we can upgrade these connections, if accepted we'll upgrade to WebSocket connection. If denied, we'll perform our requests by HTTP protocol).

We can perform https requests to our gird nodes without handle websocket connections. But, I'm not sure if we can start a WS protocol without perform the first pooling HTTP request.

Our first example performs the standard workflow:
- We start a new socket.io connection sending a HTTP pooling request asking if we can upgrade our connection (If's important to notice `upgrades` field).
- A new websocket connection will be established.
- After that, we send 8 messages using websocket protocol.
- The websocket connection will be closed by the last HTTP request
![socketio](https://user-images.githubusercontent.com/26658472/65192924-626b9500-da4f-11e9-8c75-585e7b375d9d.png)

Our second example, performs socket.io  protocol using http requests.
- We start a new socketio.io connection sending a HTTP pooling request, but now we don't want use websocket connections ( `upgrades` field is empty ).
- A websocket connection won't be estabilished.
- We perform 8 requests like we did before (but now, using HTTP protocol).
![http_requests](https://user-images.githubusercontent.com/26658472/65193317-06097500-da51-11e9-92df-a023d6d51160.png).


About performance:
- To small/unique requests, maybe, HTTP  is better than Socket.IO/Websocket connections (we can  send only one request instead of two ).
- To big/frequent requests WS/Socket.IO connections will be better.

Our small test wasn't sufficient to stress socket.io app server (we're sending small/few messages), but we can notice the difference between elapsed times (time spent to send/receive ACK message).

![socket_io_elapsed_time](https://user-images.githubusercontent.com/26658472/65195167-7665c580-da54-11e9-8ad8-97116ff26dfc.png)
![Screenshot from 2019-09-18 20-40-30](https://user-images.githubusercontent.com/26658472/65195193-9c8b6580-da54-11e9-8b20-da94baaea1d6.png)

**Comment by mari-linhares** [comment]
Thanks for the details on performance @IonesioJunior!!

Then we agree that we should have just a kind of worker, right?

Summarizing my view:
- having a worker that talks only http was a great first step, but I don't think currently we have a scenario in mind where we would use only http.
- Also, having a single client makes pyGrid easier for new starters. Currently we have tutorials using GridClients and other tutorials using WebsocketGridClients.
- For grid.js / syft.js workers need to use websockets.

**Comment by iamtrask** [comment]
+1

**Comment by cereallarceny** [comment]
I mean, I'm definitely in favor of sockets only.  It's totally up to you guys what you'd like to do.  But if we get rid of sockets, I'm afraid nothing in syft.js will be possible.  In order to establish a WebRTC P2P connection you'll need a socket server.  So if compatibility with syft.js and grid.js is a priority, sockets are required.

On a second and tangental point we can hash out offline.  Socket.io is, for all intents and purposes, a dead/dying library.  Nobody has taken over the project and the only author only has 1 day a week to take on the project (not including any language ports, just pure socket core library).  I'm not entirely sure if long-polling is a requirement of PyGrid, but if you can get away with doing a pure WebSocket solution I'd highly suggest it.  On grid.js/syft.js we don't use socket.io because of the lack of maintenance and because it's a massive library and file size is a huge concern with libraries loaded in a web browser.  Again though, that's a bit off-topic - I'm happy to pick this up offline.

**Comment by IonesioJunior** [comment]
This is a good point to be discussed. I'll create a new PR to discuss our possible trade-offs.

**Comment by IonesioJunior** [comment]
Here! #332

**Comment by cereallarceny** [comment]
@IonesioJunior Commented on 332!
