### ISSUE TITLE
Questions concerning practical implementation

### ISSUE THREAD

**Issue by patselle** [OpenMined/PyGrid#551]
Hello PyGrid-Team

I try to test PyGrid in a more practice-oriented way.
In my case this means that I want to start the different nodes (Boll, Alice and so on) via docker-compose on different physically separated devices.

This has raised the following question for me:
How should docker-compose.yml look like if only one gateway exists, i.e. how is it integrated for the different nodes?

Another questions that comes to my mind in case of a practical case is the following:

Data usually already exists on the different physically separated devices. How is it possible to provide this data to the grid (best when starting the node)?
So that it can be found via the search command over a given tag?
What about the encryption of the data at this point?
I mean, does this data have to be encrypted before it is sent to the node and if so, how is it possible for the algorithm to decrypt it within the framework of federated learning?

Greetings

Patrick

**Comment by IonesioJunior** [comment]
Hello @patselle!

"**_How should docker-compose.yml look like if only one gateway exists, i.e. how is it integrated for the different nodes?_**"

Basically, you'll need docker-compose files instead of only one (one to set up the gateway app and others to set up the grid nodes apps on different devices). 

_PS: It is worth remembering that there are automatic deployment technologies that allow you to scale the infrastructure using a single command (**ANSIBLE**, **terraform**, etc.), however, the use of these tools requires advanced devices configuration._

**_Data usually already exists on the different physically separated devices. How is it possible to provide this data to the grid (best when starting the node)?_**
Okay, The GridNodes were initially designed to work as a server to store/compute tensors which should init empty and gradually can be filled by data published on them, so the main idea goal is to serve a grid node as data service data allow users (data scientists) to work with private data without transgressing privacy-preserving concepts. But we are aware of your use case. In fact, many people have been reporting the same interest. So we have in mind to implement this soon.


**_What about the encryption of the data at this point?
I mean, does this data have to be encrypted before it is sent to the node and if so, how is it possible for the algorithm to decrypt it within the framework of federated learning?_**
That's a good one! But before I answer this question, it's important to understand how the encryption process works on PySyft/PyGrid.  We use the Secure Multi-Party Computation approach, This algorithm allows us to split some data into different anonymized pieces.
Those pieces should be sent to different workers and the original value can only be recovered by aggregating them. 
When you encrypt a tensor in PySyft, you're actually splitting the values  (by default we split into 2 pieces) and sending them to different workers. The result of this operation is a [shared_tensor](https://github.com/OpenMined/PySyft/blob/master/syft/frameworks/torch/tensors/interpreters/additive_shared.py) which stores all the remote references to the original value. Using this structure, you can recover the original value ( decryption ) by sending a request to all workers that own a piece of the encrypted data.

**Comment by patselle** [comment]
@IonesioJunior 

Thank you for your detailed answer.
