### ISSUE TITLE
Question concerning deployment scaling in practice

### ISSUE THREAD

**Issue by nattapoombeam** [OpenMined/PyGrid#711]
Hi PyGrid Team,

I was testing the deployment of a model-centric fl framework to use with mobile user clients and have a couple of questions regarding node scaling when there are large amount of incoming traffic. 

Since number of mobile clients can range up to millions of users at a particular time interval, how does PyGrid node scale up to accept all the incoming request to update the model? Will the network duplicate the node then combine the model update later using the average plan or are the number of nodes deployed remain fixed and instead scale up/spawn multiple workers within the nodes to manage the load and average the updates?
From my understanding, I assume it is the latter, but I would like to clarify to make sure.

Another question regarding this is if I am to deploy PyGrid on Google Cloud Kubernetes cluster, will I need to set kubernetes scaling configuration for the nodes image deployed? Or do I fix the number of kubernetes pods since the node and network already has its own scaling capabilities?

Thank you

**Comment by IonesioJunior** [comment]
@cereallarceny

**Comment by cereallarceny** [comment]
There is no "network" in model-centric FL, there's only a "node". This node can be deployed to multiple instances and load balanced across. Also keep in mind that while there may be millions of devices, it's more important to know how many devices are currently connected to PyGrid. If you operate your worker libraries via Websockets then scale is something you will need to think about. If it's over HTTP, I would suspect that a single instance should be able to handle the load by itself. Our worker libraries and PyGrid support both protocols.

PyGrid does not have any particular suggestion as to how to do this, since it's a pretty general question about infrastructure and not a question specific to PyGrid. I'll be closing this.
