### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by nooralahzadeh** [OpenMined/PyGrid#835]
Thera is no any docker-compose.yml file in the new update!

**Comment by jiyanxin** [comment]
I have the same problem. Did  you solve it ?

**Comment by palomilu** [comment]
Me too, I had to use the "manual" option to run a node

`cd apps/node
./run.sh --id bob --port 5000 --start_local_db`

remark: there is no 'apps/node' folder but e.g. 'apps/domain' and the --id parameter is deprecated, now there is a --name parameter

**Comment by zerjioang** [comment]
It seems they removed the file at commit 7d6d9d5f1184e472713998aeff76446f9ade3407 from the repo and README remains out of sync. Maybe @IonesioJunior  can give us more details.

**Comment by zerjioang** [comment]
In any case @nooralahzadeh @jiyanxin @palomilu , you can fetch last available docker-compose content at https://github.com/OpenMined/PyGrid/blob/788792f13042951521388884f0915e5088e86b21/docker-compose.yml

**Comment by IonesioJunior** [comment]
During the migration from version, `0.2.x` to `0.5.x` the entire architecture grid was rethought/redone. So yeah, that file was out of date considering a current architecture (If you still want to use a 0.2.x version, there is a separate branch in this repository).

Also, my apologies for the outdated documentation, I will close this issue and create a new one in order to update the README.md

If you guys, need more information about this issue, please let me know _(feel free to ping me on slack)_.
